/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
<<<<<<< HEAD
import { Route as AboutRouteImport } from './routes/about'
=======
>>>>>>> development
import { Route as StaffRouteRouteImport } from './routes/staff/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StaffPosRouteImport } from './routes/staff/pos'
<<<<<<< HEAD
import { Route as StaffOrdersRouteImport } from './routes/staff/orders'
import { Route as StaffInventoryRouteImport } from './routes/staff/inventory'
import { Route as StaffExpensesRouteImport } from './routes/staff/expenses'
=======
import { Route as AdminMenuRouteImport } from './routes/admin/menu'
>>>>>>> development
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminAccountsRouteImport } from './routes/admin/accounts'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const StaffRouteRoute = StaffRouteRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRouteRoute = StaffRouteRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const StaffPosRoute = StaffPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => StaffRouteRoute,
} as any)
<<<<<<< HEAD
const StaffOrdersRoute = StaffOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffInventoryRoute = StaffInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffExpensesRoute = StaffExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => StaffRouteRoute,
=======
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRouteRoute,
>>>>>>> development
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
<<<<<<< HEAD
  '/about': typeof AboutRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/staff/expenses': typeof StaffExpensesRoute
  '/staff/inventory': typeof StaffInventoryRoute
  '/staff/orders': typeof StaffOrdersRoute
=======
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/menu': typeof AdminMenuRoute
>>>>>>> development
  '/staff/pos': typeof StaffPosRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/staff': typeof StaffRouteRouteWithChildren
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/inventory': typeof AdminInventoryRoute
<<<<<<< HEAD
  '/staff/expenses': typeof StaffExpensesRoute
  '/staff/inventory': typeof StaffInventoryRoute
  '/staff/orders': typeof StaffOrdersRoute
=======
  '/admin/menu': typeof AdminMenuRoute
>>>>>>> development
  '/staff/pos': typeof StaffPosRoute
  '/admin': typeof AdminIndexRoute
  '/staff': typeof StaffIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
<<<<<<< HEAD
  '/about': typeof AboutRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/staff/expenses': typeof StaffExpensesRoute
  '/staff/inventory': typeof StaffInventoryRoute
  '/staff/orders': typeof StaffOrdersRoute
=======
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/menu': typeof AdminMenuRoute
>>>>>>> development
  '/staff/pos': typeof StaffPosRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/staff'
<<<<<<< HEAD
    | '/about'
    | '/admin/inventory'
    | '/staff/expenses'
    | '/staff/inventory'
    | '/staff/orders'
=======
    | '/admin/accounts'
    | '/admin/inventory'
    | '/admin/menu'
>>>>>>> development
    | '/staff/pos'
    | '/admin/'
    | '/staff/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
<<<<<<< HEAD
    | '/about'
    | '/admin/inventory'
    | '/staff/expenses'
    | '/staff/inventory'
    | '/staff/orders'
    | '/staff/pos'
    | '/admin'
    | '/staff'
=======
    | '/staff'
    | '/admin/accounts'
    | '/admin/inventory'
    | '/admin/menu'
    | '/staff/pos'
    | '/admin'
>>>>>>> development
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/staff'
<<<<<<< HEAD
    | '/about'
    | '/admin/inventory'
    | '/staff/expenses'
    | '/staff/inventory'
    | '/staff/orders'
=======
    | '/admin/accounts'
    | '/admin/inventory'
    | '/admin/menu'
>>>>>>> development
    | '/staff/pos'
    | '/admin/'
    | '/staff/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  StaffRouteRoute: typeof StaffRouteRouteWithChildren
<<<<<<< HEAD
  AboutRoute: typeof AboutRoute
=======
>>>>>>> development
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/staff/pos': {
      id: '/staff/pos'
      path: '/pos'
      fullPath: '/staff/pos'
      preLoaderRoute: typeof StaffPosRouteImport
      parentRoute: typeof StaffRouteRoute
    }
<<<<<<< HEAD
    '/staff/orders': {
      id: '/staff/orders'
      path: '/orders'
      fullPath: '/staff/orders'
      preLoaderRoute: typeof StaffOrdersRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/inventory': {
      id: '/staff/inventory'
      path: '/inventory'
      fullPath: '/staff/inventory'
      preLoaderRoute: typeof StaffInventoryRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/expenses': {
      id: '/staff/expenses'
      path: '/expenses'
      fullPath: '/staff/expenses'
      preLoaderRoute: typeof StaffExpensesRouteImport
      parentRoute: typeof StaffRouteRoute
=======
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRouteRoute
>>>>>>> development
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface StaffRouteRouteChildren {
<<<<<<< HEAD
  StaffExpensesRoute: typeof StaffExpensesRoute
  StaffInventoryRoute: typeof StaffInventoryRoute
  StaffOrdersRoute: typeof StaffOrdersRoute
  StaffPosRoute: typeof StaffPosRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteRouteChildren: StaffRouteRouteChildren = {
  StaffExpensesRoute: StaffExpensesRoute,
  StaffInventoryRoute: StaffInventoryRoute,
  StaffOrdersRoute: StaffOrdersRoute,
  StaffPosRoute: StaffPosRoute,
  StaffIndexRoute: StaffIndexRoute,
=======
  StaffPosRoute: typeof StaffPosRoute
}

const StaffRouteRouteChildren: StaffRouteRouteChildren = {
  StaffPosRoute: StaffPosRoute,
>>>>>>> development
}

const StaffRouteRouteWithChildren = StaffRouteRoute._addFileChildren(
  StaffRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  StaffRouteRoute: StaffRouteRouteWithChildren,
<<<<<<< HEAD
  AboutRoute: AboutRoute,
=======
>>>>>>> development
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
