/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedCashierRouteRouteImport } from './routes/_authed/cashier/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedCashierPosRouteImport } from './routes/_authed/cashier/pos'
import { Route as AuthedAdminAccountsRouteImport } from './routes/_authed/admin/accounts'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCashierRouteRoute = AuthedCashierRouteRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCashierPosRoute = AuthedCashierPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthedCashierRouteRoute,
} as any)
const AuthedAdminAccountsRoute = AuthedAdminAccountsRouteImport.update({
  id: '/admin/accounts',
  path: '/admin/accounts',
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cashier': typeof AuthedCashierRouteRouteWithChildren
  '/admin/accounts': typeof AuthedAdminAccountsRoute
  '/cashier/pos': typeof AuthedCashierPosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cashier': typeof AuthedCashierRouteRouteWithChildren
  '/admin/accounts': typeof AuthedAdminAccountsRoute
  '/cashier/pos': typeof AuthedCashierPosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_authed/cashier': typeof AuthedCashierRouteRouteWithChildren
  '/_authed/admin/accounts': typeof AuthedAdminAccountsRoute
  '/_authed/cashier/pos': typeof AuthedCashierPosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cashier'
    | '/admin/accounts'
    | '/cashier/pos'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cashier' | '/admin/accounts' | '/cashier/pos' | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/cashier'
    | '/_authed/admin/accounts'
    | '/_authed/cashier/pos'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/cashier': {
      id: '/_authed/cashier'
      path: '/cashier'
      fullPath: '/cashier'
      preLoaderRoute: typeof AuthedCashierRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/cashier/pos': {
      id: '/_authed/cashier/pos'
      path: '/pos'
      fullPath: '/cashier/pos'
      preLoaderRoute: typeof AuthedCashierPosRouteImport
      parentRoute: typeof AuthedCashierRouteRoute
    }
    '/_authed/admin/accounts': {
      id: '/_authed/admin/accounts'
      path: '/admin/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AuthedAdminAccountsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedCashierRouteRouteChildren {
  AuthedCashierPosRoute: typeof AuthedCashierPosRoute
}

const AuthedCashierRouteRouteChildren: AuthedCashierRouteRouteChildren = {
  AuthedCashierPosRoute: AuthedCashierPosRoute,
}

const AuthedCashierRouteRouteWithChildren =
  AuthedCashierRouteRoute._addFileChildren(AuthedCashierRouteRouteChildren)

interface AuthedRouteRouteChildren {
  AuthedCashierRouteRoute: typeof AuthedCashierRouteRouteWithChildren
  AuthedAdminAccountsRoute: typeof AuthedAdminAccountsRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedCashierRouteRoute: AuthedCashierRouteRouteWithChildren,
  AuthedAdminAccountsRoute: AuthedAdminAccountsRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
